# Generated by Django 3.2.3 on 2021-06-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='cityzenshipno',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='duty_type',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='office',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='sallery',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='sallery_type',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='shift',
        ),
    ]
