# Generated by Django 3.2.3 on 2021-06-10 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0002_auto_20210610_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='office',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr_management_app.office'),
            preserve_default=False,
        ),
    ]
