# Generated by Django 3.2.3 on 2021-06-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management_app', '0005_auto_20210610_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='office_id',
        ),
    ]
